//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My_Custom_List_by_MCF___stud_.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Liste faite par Marie Dr en animés.
Made in abyss'
Gurren Lagann
Shen Gate
My hero academia
Evangelion
Plandre - Space Dandy
Haikyu
Psycho-pass
Death Parade
Gungrave
Rainbow
Blue Exorcist
Full Metal Alchimist : Brotherhood
Hunter x Hunter (2011)
hellsing ultimate
Barakamon
Mushishi
Avatar : Le dernier maître / Monstre de l'air
GTO
Samuraï Shamploo
Cowboy bebop
Durarara
Dororo
Ace no diamond
Black lagon
Yakwsoku no neverland
L'attaque des titans (Shinguki)
One punch man (saison 1)
Mob psycho 100
Usagi Drop")]
        public string AnimeList {
            get {
                return ((string)(this["AnimeList"]));
            }
            set {
                this["AnimeList"] = value;
            }
        }
    }
}
